### ISSUE TITLE
KeyError: 'version'

### ISSUE THREAD

**Issue by ravitejamandapati** [PureStorage-OpenConnect/rest-client#11]
While connecting to array, we are getting below error.

#array = purestorage.FlashArray("xxxxxxxxxxxx", "pureuser", "pureuser")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/purestorage/purestorage.py", line 138, in __init__
    self._rest_version = self._choose_rest_version()
  File "/opt/anaconda3/lib/python3.7/site-packages/purestorage/purestorage.py", line 217, in _choose_rest_version
    versions = self._list_available_rest_versions()
  File "/opt/anaconda3/lib/python3.7/site-packages/purestorage/purestorage.py", line 231, in _list_available_rest_versions
    return data["version"]
KeyError: 'version'

**Comment by zolstein** [comment]
What version of Purity do you have installed on your array?

**Comment by ravitejamandapati** [comment]
Version  Revision
2.1.9    2018.03.16_8db6052d

**Comment by zolstein** [comment]
It looks like you tried to connect to a FlashBlade. This client only works with FlashArray. We have a separate REST client for communicating with FlashBlade, available [here](https://pypi.org/project/purity_fb/).

**Comment by ravitejamandapati** [comment]
Thank You. I can able to connect with blade now.
